apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.protocol}}
spec:
  rules:
  - http:
      paths:
      - path: "/*"
        backend:
          serviceName: {{ .Values.ingress.backend.service}}
          servicePort: {{ .Values.ingress.backend.port}}
