apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gamesInfo.fullname" . }}-ingress-certificate
  labels:
    app: {{ .Values.global.appName}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls_secret/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls_secret/tls.key" | b64enc }}