apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "gamesInfo.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.protocol}}
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: {{ .Values.ingress.path}}
        backend:
          serviceName: {{ .Values.ingress.backend.service}}
          servicePort: {{ .Values.ingress.backend.port}}