apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamesInfo.fullname" . }}-mailsender-deploy
  labels:
    app: {{.Values.global.appName}}
    tier: {{.Values.mailSender.tier}}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.global.appName}}
      tier: {{ .Values.mailSender.tier}}
  replicas: {{ .Values.mailSender.replicaCount}}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName}}
        tier: {{ .Values.mailSender.tier}}
    spec:
      containers:
      - name: {{ include "gamesInfo.fullname" . }}-mailsender-container
        image: "{{ .Values.mailSender.image.repository}}:{{ .Values.mailSender.image.tag}}"
        imagePullPolicy: {{ .Values.mailSender.image.pullPolicy}}
        ports:
        - containerPort: {{ .Values.mailSender.ports.internalPort}}
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup jlojosnegros-jlojosnegros-mysql; do echo waiting for mysql; sleep 2; done;']