apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamesInfo.fullname" .}}
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.mailSender.tier}}
spec:
  ports:
  - port: {{ .Values.mailSender.ports.internalPort}}
    protocol: TCP
    name: "{{.Values.global.appName}}-mailport"
  selector:
    app: {{ .Values.global.appName}}
  type: {{ .Values.mailSender.serviceType}}