apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamesInfo.fullname" .}}
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.mailSender.tier}}
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: "{{.Values.global.appName}}-webport"
  selector:
    app: {{ .Values.global.appName}}
    type: {{ .Values.mailSender.serviceType}}