apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    type: local
    app: {{ .Values.global.appName}}
spec:
  storageClassName: {{ .Values.pv.storageClass}}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.path}}