apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamesInfo.fullname" . }}-webfe-svc
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
spec:
  ports:
  - name: hazelcast
    port: 5701
  - name: "{{.Values.global.appName}}-webport"
    port: {{ .Values.webFE.port}}
  selector:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
  type: {{ .Values.webFE.serviceType}}