apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamesInfo.fullname" . }}-webfe-svc
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
spec:
  ports:
  - port: {{ .Values.webFE.port}}
    name: "{{.Values.global.appName}}-webport"
  selector:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
  type: {{ .Values.webFE.serviceType}}