apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamesInfo.fullname" . }}
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.global.appName}}
      tier: {{ .Values.mailSender.tier}}
  replicas: {{ .Values.webFE.replicaCount}} # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: {{ .Values.global.appName}}
    spec:
      containers:
      - name: 
        image: "{{ .Values.webFE.image.repository}}:{{ .Values.webFE.image.tag}}"
        imagePullPolicy: {{ .Values.webFE.image.pullPolicy}}
        ports:
        - containerPort: {{ .Values.webFE.ports.internalPort}}