apiVersion: v1
kind: Service
metadata:
  name: {{ include "gamesInfo.fullname" .}}
  labels:
    app: {{ .Values.global.appName}}
    tier: {{ .Values.webFE.tier}}
spec:
  ports:
  - port: {{ .Values.webFE.ports.internalPort}}
    targetPort: {{ .Values.webFE.ports.exposedPort}}
    protocol: TCP
    name: "{{.Values.global.appName}}-webport"
  selector:
    app: {{ .Values.global.appName}}
  type: {{ .Values.webFE.serviceType}}