# Default values for gamesInfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appName: jlojosnegros

webFE:
  replicaCount: 2
  tier: front-end
  image:
    repository: jlojosnegros/prueba_servidor
    tag: latest
    pullPolicy: IfNotPresent
  serviceType: LoadBalancer

mailSender:
  replicaCount: 2
  tier: back-end
  image:
    repository: jlojosnegros/mailservice
    tag: latest
    pullPolicy: IfNotPresent
  serviceType: ClusterIP

database:
  tier: ddbb

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "mierda-pura"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
